apiVersion: v1
kind: Namespace
metadata:
  name: scenario-keyvault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvault-demo-sa
  namespace: scenario-keyvault
  annotations:
    azure.workload.identity/client-id: "e2737e48-3d21-4b6b-97dc-67f6c2d92640"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secret-provider
  namespace: scenario-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "e2737e48-3d21-4b6b-97dc-67f6c2d92640"
    keyvaultName: "aks-ghcp-demo-kv"
    tenantId: "5340213a-3d15-4409-b601-986b20e741af"
    objects: |
      array:
        - |
          objectName: demo-secret
          objectType: secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault-demo
  namespace: scenario-keyvault
  labels:
    scenario: keyvault-secret-volume
    app: keyvault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvault-demo
      scenario: keyvault-secret-volume
  template:
    metadata:
      labels:
        app: keyvault-demo
        scenario: keyvault-secret-volume
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: keyvault-demo-sa
      containers:
      - name: app
        image: ghcpdemoacr.azurecr.io/keyvault-demo:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keyvault-secret-provider
